"""
Django settings for djangoApp project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from decouple import config  # pip install python-decouple
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


VAPID_PUBLIC_KEY = config("VAPID_PUBLIC_KEY")
VAPID_PRIVATE_KEY = config("VAPID_PRIVATE_KEY")
VAPID_CLAIMS = {"sub": config("VAPID_CLAIM_SUB")}

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "192.168.8.183",
    "192.168.8.9",
    "192.168.45.183",
    "192.168.45.9",
]


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "simple": {
            "format": "[{levelname}] {name}:{lineno} {message}",
            "style": "{",
        },
    },
    "loggers": {
        # Django 요청
        "django": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        # Channels/WebSocket 라우터
        "channels": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
        "channels.routing": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    },
}

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": config("DB_NAME", default="alpaca_car"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="3306"),
    }
}
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    # Custom 앱
    "accounts",
    "streamapp",
    # allauth 기본
    # "allauth",
    # "allauth.account",
    # "allauth.socialaccount",
    # 소셜 프로바이더
    # "allauth.socialaccount.providers.google",
    # "allauth.socialaccount.providers.kakao",
    # DRF + JWT
    "rest_framework",
    "rest_framework.authtoken",
    "rest_framework_simplejwt",
    # "rest_framework_simplejwt.token_blacklist",
    # dj-rest-auth
    # "dj_rest_auth",
    # "dj_rest_auth.registration",
]
# allauth
SITE_ID = 1
REST_USE_JWT = True
ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_EMAIL_REQUIRED = True
AUTH_USER_MODEL = "accounts.Member"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": "<GOOGLE_CLIENT_ID>",
            "secret": "<GOOGLE_CLIENT_SECRET>",
            "key": "",
        }
    },
    "kakao": {
        "APP": {
            "client_id": "<KAKAO_CLIENT_ID>",
            "secret": "<KAKAO_CLIENT_SECRET>",
            "key": "",
        }
    },
}

# dj‑rest‑auth 소셜 설정
REST_USE_JWT = True
JWT_AUTH_COOKIE = None  # 쿠키가 아닌 헤더로

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # ── allauth용 미들웨어 ──
    # "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "djangoApp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "djangoApp.wsgi.application"
ASGI_APPLICATION = "djangoApp.asgi.application"

# WebSocket을 위해 최소한 In‑Memory 레이어 추가
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
