# Generated by Django 5.2.4 on 2025-08-06 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarNumberPlateModelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=255, unique=True, verbose_name='차량 번호판')),
                ('model', models.ForeignKey(db_column='model_id', on_delete=django.db.models.deletion.CASCADE, related_name='plate_mappings', to='vehicles.vehiclemodel', verbose_name='모델')),
            ],
            options={
                'verbose_name': '번호판-모델 매핑',
                'verbose_name_plural': '번호판-모델 매핑',
                'db_table': 'car_number_plate_model_mapping',
            },
        ),
    ]
