# Generated by Django 5.2.4 on 2025-07-29 08:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='입차 시각')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='출차 시각')),
                ('status', models.CharField(choices=[('ASSIGNED', '배정됨'), ('COMPLETED', '완료됨')], default='ASSIGNED', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': '주차 배정',
                'verbose_name_plural': '주차 배정',
                'db_table': 'parking_assignment',
            },
        ),
        migrations.CreateModel(
            name='ParkingAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='변경된 점수', verbose_name='점수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='변경 시각')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parking.parkingassignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '배정 점수 히스토리',
                'verbose_name_plural': '배정 점수 히스토리',
                'db_table': 'parking_assignment_history',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=10, verbose_name='구역')),
                ('slot_number', models.PositiveIntegerField(verbose_name='슬롯 번호')),
                ('size_class', models.CharField(choices=[('compact', 'Compact'), ('midsize', 'Midsize'), ('suv', 'SUV')], max_length=10, verbose_name='허용 크기')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='점유 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '주차 공간',
                'verbose_name_plural': '주차 공간',
                'db_table': 'parking_space',
                'unique_together': {('zone', 'slot_number')},
            },
        ),
        migrations.AddField(
            model_name='parkingassignment',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='parking.parkingspace'),
        ),
    ]
