# Generated by Django 5.2.4 on 2025-08-11 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_vehicleevent_options_and_more'),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingassignment',
            name='entrance_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='events.vehicleevent'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='status',
            field=models.CharField(choices=[('free', '비어있음'), ('occupied', '사용중'), ('reserved', '예약됨')], default='free', max_length=10, verbose_name='상태'),
        ),
    ]
