# Generated by Django 5.2.4 on 2025-08-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("free", "비어있음"),
                    ("occupied", "사용중"),
                    ("reserved", "예약됨"),
                ],
                default="free",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
