# Generated by Django 5.2.4 on 2025-08-11 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingassignment_entrance_event_and_more'),
        ('vehicles', '0002_vehiclelicenseplatemodelmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='current_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_space', to='vehicles.vehicle'),
        ),
    ]
