# Generated by Django 5.2.4 on 2025-08-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingspace_status'),
        ('parking', '0003_parkingspace_current_vehicle'),
    ]

    operations = [
    ]
