# Generated by Django 5.2.4 on 2025-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0004_merge_20250813_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("free", "free"),
                    ("occupied", "occupied"),
                    ("reserved", "reserved"),
                ],
                default="free",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
