# Generated by Django 5.2.4 on 2025-08-15 19:07

import parking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0005_alter_parkingspace_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingassignment",
            name="start_time",
            field=models.DateTimeField(
                default=parking.models.get_korean_now, verbose_name="입차 시각"
            ),
        ),
    ]
