# Generated by Django 5.2.4 on 2025-07-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Entrance', '입차'), ('Exit', '출차'), ('Exception', '예외')], max_length=20, verbose_name='이벤트 종류')),
                ('timestamp', models.DateTimeField(verbose_name='발생 시각')),
                ('vehicle', models.ForeignKey(db_column='vehicle_id', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vehicles.vehicle', verbose_name='차량')),
            ],
            options={
                'verbose_name': '차량 이벤트',
                'verbose_name_plural': '차량 이벤트',
                'db_table': 'vehicle_event',
            },
        ),
    ]
