# Generated by Django 5.2.4 on 2025-08-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleevent',
            name='event_type',
            field=models.CharField(choices=[('Entrance', '입차'), ('Parking', '주차완료'), ('Exit', '출차'), ('Exception', '예외')], max_length=20, verbose_name='이벤트 종류'),
        ),
    ]
