# Generated by Django 5.2.4 on 2025-08-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_vehicleevent_event_type"),
        ("vehicles", "0002_vehiclelicenseplatemodelmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicleevent",
            options={},
        ),
        migrations.RemoveField(
            model_name="vehicleevent",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="vehicleevent",
            name="timestamp",
        ),
        migrations.AddField(
            model_name="vehicleevent",
            name="entrance_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleevent",
            name="exit_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleevent",
            name="parking_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicleevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("Entrance", "입차"),
                    ("Parking", "주차완료"),
                    ("Exit", "출차"),
                    ("Exception", "예외"),
                ],
                default="Entrance",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="vehicleevent",
            name="vehicle",
            field=models.ForeignKey(
                db_column="vehicle_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="vehicles.vehicle",
            ),
        ),
    ]
