# Generated by Django 5.2.4 on 2025-08-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_notification_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', '시스템'), ('parking_assigned', '주차 배정'), ('parking_complete', '주차 완료'), ('entry', '입차 알림'), ('exit', '출차 완료'), ('warning', '경고'), ('general', '일반')], default='system', max_length=20, verbose_name='알림 종류'),
        ),
    ]
